
return{
	"folke/snacks.nvim",
	priority = 1000,
	event = "VeryLazy",
	opts = {
		animate = { enabled = true },
		bigfile = { enabled = true },
		dashboard = { enabled = true },
		hints = {enabled= true},
		lazygit = { enabled = true },
		indent = { enabled = true },
		input = { enabled = true },
		notifier = { enabled = false },
		quickfile = { enabled = true },
		scroll = { enabled = true },
		statuscolumn = { enabled = true },
		words = { enabled = true },
		terminal = { enabled = false },
		picker = {enabled = true},
    image = {enabled = true},
	},
	keys = {
    --pickers 
		{ "<leader>ff", function() Snacks.picker.files() end, desc = "Find Files" },
		{ "<leader>fr", function() Snacks.picker.recent() end, desc = "Recent Files" },
		{ "<leader>fk", function() Snacks.picker.keymaps() end, desc = "Find Keymaps" },
		{ "<leader>fc", function() Snacks.picker.commands() end, desc = "Find Commands" },
		{ "<leader>fm", function() Snacks.picker.marks() end, desc = "Find Marks" },
		{ "<leader>fR", function() Snacks.picker.registers() end, desc = "Find Registers" },
		{ "<leader>rg", function() Snacks.picker.grep() end, desc = "Search text in project" },
		{ "<leader>rw", function() Snacks.picker.grep_word() end, desc = "Ripgrep Word Under Cursor" },
		{ "<leader>rb", function() Snacks.picker.grep_buffers() end, desc = "Ripgrep Open Buffers" },
		{ "<leader>rh", function() Snacks.picker.search_history() end, desc = "Ripgrep Search History" },
		{ "<leader>rp", function() Snacks.picker.resume() end, desc = "Resume Last Search" },
		{ "<leader>ft", function() Snacks.picker.lines() end, desc = "Buffer Lines" },
    {"<leader>fw", function() Snacks.picker.grep_word() end, desc = "Find string under cursor in project"},
    {"<leader>fb", function() Snacks.picker.buffers() end, desc = "List open buffers"},
		{ "<leader>st", function() require("nvchad.themes").open() end, desc = "NvChad Theme Switcher" },
    {"<leader>fh", function () Snacks.picker.help() end, desc="Search help tags"},
    {"<leader>fo", function() Snacks.picker.todo_comments() end, desc = "show todo comments"},

		{ "<leader>z",  function() Snacks.zen() end, desc = "Toggle Zen Mode" },
		{ "<leader>sc",  function() Snacks.scratch() end, desc = "Toggle Scratch Buffer" },
		{ "<leader>nl",  "<cmd>Noice history<CR>", desc = "Notification History" },
		{ "<leader>nh", "<cmd>Noice dismiss<CR>", desc = "Dismiss All Notifications" },
    {"<leader>gl", function () Snacks.lazygit.open() end, desc = "Open Lazygit"},
	},
}
